apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      pod: app-deployment
  template:
    metadata:
      labels:
        pod: app-deployment
    spec:
      containers:
        - name: app-deployment-container
          imagePullPolicy: Always
          image: gcr.io/analytics-team-253708/app-demo
