apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      pod: client-deployment
  template:
    metadata:
      labels:
        pod: client-deployment
    spec:
      containers:
        - name: client-deployment-container
          imagePullPolicy: Always
          image: gcr.io/analytics-team-253708/client-demo
