apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-fanout-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: nginx-static-ip
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: app
              servicePort: 5000
          - path: /server(/|$)(.*)
            backend:
              serviceName: server
              servicePort: 5000